const data = [
	{
		topicName: "Quantitative Aptitude",
		position: 0,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Numbers",
				Problem: "Problems Related to Numbers",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/numbers-gq/",
			},
			{
				Topic: "LCM and HCF",
				Problem: "Problems Related to Lcm and Hcf",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/lcm-gq/",
			},
			{
				Topic: "Work and Wages",
				Problem: "Problems Related to Work and Wages",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/work-and-wages-gq/",
			},
			{
				Topic: "Pipes and Cisterns ",
				Problem: "Problems Related to Pipes and Cisterns ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/pipes-and-cisterns-gq/",
			},
			{
				Topic: "Time Speed Distance",
				Problem: "Problems Related to Time Speed Distance",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/time-speed-distance-gq/",
			},
			{
				Topic: "Trains, Boats, and Streams",
				Problem: "Problems Related to Trains, Boats, and Streams",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/trains-boats-and-streams-2-gq/",
			},
			{
				Topic: "Percentages",
				Problem: "Problems Related to Percentages",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/percentages-gq/",
			},
			{
				Topic: "Ratio Proportion and Partnership",
				Problem: "Problems Related to Ratio Proportion and Partnership",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/ratio-and-proportion-gq/",
			},
			{
				Topic: "Algebra",
				Problem: "Problems Related to Algebra",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/algebra-gq/",
			},
			{
				Topic: "Profit and Loss",
				Problem: "Problems Related to Profit and Loss",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/profit-and-loss-gq/",
			},
			{
				Topic: "Age",
				Problem: "Problems Related to Age",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/age-gq/",
			},
			{
				Topic: "Simple Interest",
				Problem: "Problems Related to Simple Interest",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/simple-interest-gq/",
			},
			{
				Topic: "Permutation and Combination",
				Problem: "Problems Related to Permutation and Combination",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/permutation-and-combination-gq/",
			},
			{
				Topic: "Probability",
				Problem: "Problems Related to Probability",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/probability-3-gq/",
			},
			{
				Topic: "Clocks",
				Problem: "Problems Related to Clocks",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/clocks-clocks-clocks-gq/",
			},
			{
				Topic: "Calendars",
				Problem: "Problems Related to Calendars",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/calendars-gq/",
			},
			{
				Topic: "",
				Problem: "Problems Related to",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "",
			},
			{
				Topic: "Coding-Decoding",
				Problem: "Problems Related to Coding-Decoding",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/coding-decoding/",
			},
			{
				Topic: "Race",
				Problem: "Problems Related to Race",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/race-gq/",
			}
        ]
    },
	{
		topicName: "Verbal Ability",
		position: 1,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Passage/Sentence Rearrangement",
				Problem: "Problem related to Passage/Sentence Rearrangement ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: " https://www.geeksforgeeks.org/passagesentence-re-arrangement-english/",
			},
			{
				Topic: "Error Detection and Correction",
				Problem: "Problem related to Error Detection and Correction ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/error-detection-correction/",
			},
			{
				Topic: "Fill in the Blanks ",
				Problem: "Problem related to Fill in the Blanks ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/fill-blanks-english/",
			},
			{
				Topic: "Comprehension Passages",
				Problem: "Problem related to Comprehension Passages ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/comprehension-passages/",
			},
			{
				Topic: "Antonyms and synonyms ",
				Problem: "Problem related to Antonyms and synonyms ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: " https://www.geeksforgeeks.org/important-synonyms-and-antonyms-for-ssc-exams/",
			},
			{
				Topic: "Vocabulary and grammar",
				Problem: "Problem related to Vocabulary and grammar",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: " https://www.geeksforgeeks.org/english-grammar/",
			},
			{
				Topic: "One word Substitution",
				Problem: "Problem related to One word Substitution",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: " https://www.geeksforgeeks.org/important-one-word-substitution-for-competitive-exams/",
			}
        ]
    },
	{
		topicName: "Logical Reasoning",
		position: 2,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Data Sufficiency",
				Problem: "Problems related to Data Sufficiency",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/data-sufficiency-gq/",
			},
			{
				Topic: "Puzzles",
				Problem: "Problems related to Puzzles",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/category/puzzles/",
			},
			{
				Topic: "Syllogism",
				Problem: "Problems related to Syllogism",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/syllogism-gq/",
			},
			{
				Topic: "Alphanumeric series",
				Problem: "Problems related to Alphanumeric series",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/aptitude-for-placements/geeksforgeeks.org/alphanumeric-series/",
			},
			{
				Topic: "Blood Relations",
				Problem: "Problems related to Blood Relations",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/placement-reasoning-blood-relationship/",
			},
			{
				Topic: "Dices",
				Problem: "Problems related to Dices",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/the-dice-problem/",
			},
			{
				Topic: "Deductive Reasoning",
				Problem: "Problems related to Deductive Reasoning/",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/statements-mathematical-reasoning/",
			}
        ]
    },
	{
		topicName: "Future update topic",
		position: 3,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "coming soon..",
				Problem: " ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: " ",
			}
        ]
    }
]

export const version = 1000000817;
export default data;