const data = [
	{
		topicName: "Operating System",
		position: 0,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "OS Basics",
				Problem: "What is operating system",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/what-is-an-operating-system/",
			},
			{
				Topic: "Structure of Operating System",
				Problem: "Operating system services",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/operating-system-services/?ref=lbp",
			},
			{
				Topic: "Types of OS",
				Problem: "Different os systems",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/batch-processing-operating-system/?ref=lbp",
			},
			{
				Topic: "Process Management",
				Problem: "Process Management in os",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/introduction-of-process-management/?ref=lbp",
			},
			{
				Topic: "CPU Scheduling in OS",
				Problem: "CPU Scheduling in OS",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/cpu-scheduling-in-operating-systems/?ref=lbp",
			},
			{
				Topic: "Threads in OS",
				Problem: "Threads in OS",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/thread-in-operating-system/?ref=lbp",
			},
			{
				Topic: "Process Synchronization",
				Problem: "Process Synchronization in os",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/introduction-of-process-synchronization/?ref=lbp",
			},
			{
				Topic: "Critical Section Problem Solution",
				Problem: "Critical Section Problem Solution",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/petersons-algorithm-in-process-synchronization/?ref=lbp",
			},
			{
				Topic: "Deadlocks & Deadlock Handling Methods",
				Problem: "Deadlocks & Deadlock Handling Methods",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/introduction-of-deadlock-in-operating-system/?ref=lbp",
			},
			{
				Topic: "Memory Management",
				Problem: "Memory Management",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/memory-management-in-operating-system/?ref=lbp",
			},
			{
				Topic: "Page Replacement Algorithms",
				Problem: "Page Replacement Algorithms",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/page-replacement-algorithms-in-operating-systems/?ref=lbp",
			},
			{
				Topic: "Storage Management",
				Problem: "Storage Management",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/storage-management/?ref=lbp",
			}
        ]
    },
	{
		topicName: "Computer Networks",
		position: 1,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Basics",
				Problem: " Basics of Computer Networking",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#basics",
			},
			{
				Topic: "Data Link Layer",
				Problem: "Data Link Layer ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#dll",
			},
			{
				Topic: "Network Layer",
				Problem: " Network Layer",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#nl",
			},
			{
				Topic: "Transport Layer",
				Problem: " Transport Layer",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#tl",
			},
			{
				Topic: "Application Layer",
				Problem: "Application Layer",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#al",
			},
			{
				Topic: "",
				Problem: " ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "",
			},
			{
				Topic: "Network Security and Cryptography",
				Problem: " Network Security and Cryptography",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#nsc",
			},
			{
				Topic: "Compression Techniques",
				Problem: "Compression Techniques ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#ct",
			},
			{
				Topic: "Network Experiments",
				Problem: "Network Experiments ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#ne",
			},
			{
				Topic: "Devices",
				Problem: " Devices",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/computer-network-tutorials/?ref=lbp#devices",
			}
        ]
    },
	{
		topicName: "Compiler Design",
		position: 2,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Introduction",
				Problem: "Introduction",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#int",
			},
			{
				Topic: "Lexical Analysis",
				Problem: "Lexical Analysis",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#la",
			},
			{
				Topic: "Syntax Analysis",
				Problem: "Syntax Analysis",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#sa",
			},
		
			{
				Topic: "Syntax Directed Translation",
				Problem: "Syntax Directed Translation",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#sdt",
			},
			{
				Topic: "Code Generation and Optimization",
				Problem: "Code Generation and Optimization",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#cgo",
			},
			{
				Topic: "Runtime Environments",
				Problem: "Runtime Environments",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#re",
			},
			{
				Topic: "Quick Links",
				Problem: "Quick Links",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/compiler-design-tutorials/?ref=lbp#ql",
			}
        ]
    },
	{
		topicName: "Database Managment System",
		position: 3,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Introduction",
				Problem: " Introduction",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#int",
			},
			{
				Topic: "Entity Relationship Model",
				Problem: " Entity Relationship Model",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#ermodel",
			},
			{
				Topic: "Relational Model",
				Problem: "Relational Model ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#rm",
			},
			{
				Topic: "Relational Algebra",
				Problem: "Relational Algebra ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#ra",
			},
			{
				Topic: "Functional Dependencies",
				Problem: " Functional Dependencies",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#fd",
			},
			{
				Topic: "Normalisation",
				Problem: "Normalisation ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#nor",
			},
			{
				Topic: "Transactions and Concurrency Control",
				Problem: " Transactions and Concurrency Control",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#tcc",
			},
			{
				Topic: "Indexing, B and B+ trees",
				Problem: "Indexing, B and B+ trees ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#btree",
			},
			{
				Topic: "File Organization",
				Problem: " File Organization",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#forg",
			},
			{
				Topic: "Advanced Topics",
				Problem: " Advanced Topics",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#adv",
			},
			{
				Topic: "SQL",
				Problem: " SQL",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#sqlt",
			},
			{
				Topic: "Quick Links",
				Problem: "Quick Links ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/dbms/?ref=lbp#ql",
			}
        ]
    }
]

export const version = 100000017;
export default data;